core/urls.py
from django.urls import path, reverse_lazy
from . import views
from .views import PasswordsChangeView
from django.contrib.auth.views import (
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView)

app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),
    path("core/entry", views.entry, name="entry"),
    path("accounts/logout/", views.logout_request, name="logout_request"),
    path("accounts/login/", views.login_request, name="login_request"),
    path("register/", views.register, name="register"),
    path("profile/", views.profile, name="profile"),
    path(
        "profile/password/",
        PasswordsChangeView.as_view(
            template_name='accounts/password_change.html'
        )
    ),
    path(
        "accounts/password_changed/",
        views.password_changed,
        name="password_changed"),
    path(
        "accounts/password-reset/",
        PasswordResetView.as_view(
            template_name='accounts/password_reset.html',
            success_url=reverse_lazy('core:password_reset_done')
        ),
        name='password_reset'
    ),
    path(
        "accounts/password-reset/done/",
        PasswordResetDoneView.as_view(
            template_name='accounts/password_reset_done.html'
        ),
        name='password_reset_done'),
    path(
        "accounts/password-reset-confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name='accounts/password_reset_confirm.html',
            success_url=reverse_lazy('core:password_reset_complete')
        ),
        name='password_reset_confirm'),
    path(
        "accounts/password-reset-complete/",
        PasswordResetCompleteView.as_view(
            template_name='accounts/password_reset_complete.html'
        ),
        name='password_reset_complete'),
    path("contact/", views.contact, name='contact'),
    path("member_stats/", views.member_stats, name='member_stats'),
    path("members/", views.members, name='members'),
    path("finance_chart/", views.finance_chart, name='finance_chart'),
    path("finances/", views.finances, name='finances'),
    path("calendar/", views.calendar, name='calendar'),
]

htmx_urlpatterns = [
    path(
        'register/check_username/', views.check_username, name='check_username'
        ),
    path(
        'register/check_email/', views.check_email, name='check_email'
        ),
]

urlpatterns += htmx_urlpatterns

proj/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',  include('core.urls')),
]

if settings.DEBUG:
    urlpatterns  += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/accounts/password_change.html
{% extends 'core/layout.html' %}
{% load static %}
{% block title %} Password Change {% endblock %}
{% block body %}
<div class="page-content">
<legend class="border-bottom mb-4">
   Password Change
</legend>
    <form method="POST">
        {% csrf_token %}
        <p>Old Password: {{ form.old_password }}</p>
        <p>New Password: {{ form.new_password1 }}</p>
        <div style="background-color:lightgray;">
            <ul>
                <li>Your password can’t be too similar to your other personal information.</li>
                <li>Your password must contain at least 8 characters.</li>
                <li>Your password can’t be a commonly used password.</li>
                <li>Your password can’t be entirely numeric.</li>
            </ul>
        </div>
        <p>New password confirmation: {{ form.new_password2 }}</p>
        <button class="btn btn-sm btn-primary" type="submit">Change My Password</button>
    </form>
</div>
{% endblock %}

templates/accounts/password_changed.html
{% extends 'core/layout.html' %}
{% load static %}
{% block title %} Password Changed {% endblock %}
{% block body %}
<div class="page-content">
<legend class="border-bottom mb-4">
   Password Changed
</legend>
    <div>
      <p>
          Your password was successfully changed.
      </p>
    </div>
    <a
      href="{% url 'core:index' %}"
      class="btn btn-sm btn-primary"
      role="button"
      type="submit"
    >
      Return to Home Page
    </a>
</div>
{% endblock %}

templates/accounts/password_reset.html
{% extends 'core/layout.html' %}
{% load static %}
{% block title %} Password Reset {% endblock %}
{% block body %}
<div class="page-content">
  <legend class="border-bottom mb-4">
    Password Reset
  </legend>
  <p>Forgotten your password?  Enter your email address below, and we'll email instructions for setting a new one.</p>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <button class="btn btn-sm btn-primary" type="submit">Reset My Password</button>
  </form>
</di>
{% endblock %}

templates/accounts/password_reset_complete.html
{% extends 'core/layout.html' %}
{% load static %}
{% block body %}
<div class="page-content">
<legend class="border-bottom mb-4">
   Password Reset Complete
</legend>
  <p>Your password has been set. You may go ahead and log in now</p>
   <a href="{% url 'core:login_request' %}">Login</a>
</div>
{% endblock %}

templates/accounts/password_reset_confirm.html
{% extends 'core/layout.html' %}
{% load static %}
{% block body %}
<div class="page-content">
  {% if validlink %}
  <legend class="border-bottom mb-4">
     Reset Password
  </legend>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button class="btn btn-sm btn-primary" type="submit">Reset Password</button>
    </form>
  {% else %}
    <p>
      The password reset link was invalid, possibly because it has already been used.
      Please request a new password reset.
    </p>
  {% endif %}
</div>
{% endblock %}

templates/accounts/password_reset_done.html
{% extends 'core/layout.html' %}
{% load static %}
{% block title %}Email Sent{% endblock %}
{% block body %}
<div class="page-content">
  <legend class="border-bottom mb-4">
     Password Sent
  </legend>
  	<div>
		    <p>
            An email has been sent with instructions to reset your password.
        </p>
	</div>
</div>
{% endblock %}