core/urls.py
from django.urls import path, reverse_lazy
from . import views
from .views import PasswordsChangeView
from django.contrib.auth.views import (
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView)

app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),
    path("core/entry", views.entry, name="entry"),
    path("accounts/logout/", views.logout_request, name="logout_request"),
    path("accounts/login/", views.login_request, name="login_request"),
    path("register/", views.register, name="register"),
    path("profile/", views.profile, name="profile"),
    path(
        "profile/password/",
        PasswordsChangeView.as_view(
            template_name='accounts/password_change.html'
        )
    ),
    path(
        "accounts/password_changed/",
        views.password_changed,
        name="password_changed"),
    path(
        "accounts/password-reset/",
        PasswordResetView.as_view(
            template_name='accounts/password_reset.html',
            success_url=reverse_lazy('core:password_reset_done')
        ),
        name='password_reset'
    ),
    path(
        "accounts/password-reset/done/",
        PasswordResetDoneView.as_view(
            template_name='accounts/password_reset_done.html'
        ),
        name='password_reset_done'),
    path(
        "accounts/password-reset-confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name='accounts/password_reset_confirm.html',
            success_url=reverse_lazy('core:password_reset_complete')
        ),
        name='password_reset_confirm'),
    path(
        "accounts/password-reset-complete/",
        PasswordResetCompleteView.as_view(
            template_name='accounts/password_reset_complete.html'
        ),
        name='password_reset_complete'),
    path("contact/", views.contact, name='contact'),
    path("member_stats/", views.member_stats, name='member_stats'),
    path("members/", views.members, name='members'),
    path("finance_chart/", views.finance_chart, name='finance_chart'),
    path("finances/", views.finances, name='finances'),
    path("calendar/", views.calendar, name='calendar'),
]

htmx_urlpatterns = [
    path(
        'register/check_username/', views.check_username, name='check_username'
        ),
    path(
        'register/check_email/', views.check_email, name='check_email'
        ),
]

urlpatterns += htmx_urlpatterns

proj/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',  include('core.urls')),
]

if settings.DEBUG:
    urlpatterns  += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/forms.py
from django import forms
from django.contrib.auth.forms import (
    AuthenticationForm, UserCreationForm, UserChangeForm
)
from django.contrib.auth.models import User
from .models import Profile, Contact
from django.core.exceptions import ValidationError
from captcha.fields import ReCaptchaField
from core.tasks import send_registration_email_task


class AuthenticationFormWithCaptchaField(AuthenticationForm):
    captcha = ReCaptchaField(
        public_key='6Le6CNkdAAAAAM0erjmCJJ_YW_tnVDhfFmvYHEQX',
        private_key='6Le6CNkdAAAAAKUVozivgonzS4yEnlfH8Ai0Ck2Y',
    )


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)
    captcha = ReCaptchaField(
        public_key='6Le6CNkdAAAAAM0erjmCJJ_YW_tnVDhfFmvYHEQX',
        private_key='6Le6CNkdAAAAAKUVozivgonzS4yEnlfH8Ai0Ck2Y',
    )

    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
            "password1",
            "password2"
        )

    def send_registration_email(self):
        send_registration_email_task.delay(
            self.cleaned_data['first_name'],
            self.cleaned_data['last_name'],
            self.cleaned_data['username'],
            self.cleaned_data['email']
        )

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.is_active = False # REMOVE LINE TO ALLOW USERS AUTO ACCESS TO APP
        if commit:
            user.save()
            return user


# Create a UserUpdateForm to update a username and email
class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']



class ProfileUpdateForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = (
            'image',
            'gender',
            'marital_status',
            'street_number',
            'street_name',
            'usr_city',
            'usr_state',
            'postal_code'
        )


class ContactForm(forms.ModelForm):
    captcha = ReCaptchaField(
        public_key='6Le6CNkdAAAAAM0erjmCJJ_YW_tnVDhfFmvYHEQX',
        private_key='6Le6CNkdAAAAAKUVozivgonzS4yEnlfH8Ai0Ck2Y',
    )

    class Meta:
        model = Contact
        fields = (
            'fullname',
            'contact_email',
            'contact_subject',
            'contact_message'
        )

    def save(self, commit=True):
        contact = super(ContactForm, self).save(commit=False)
        contact.fullname = self.cleaned_data['fullname']
        contact.contact_email = self.cleaned_data['contact_email']
        contact.contact_subject = self.cleaned_data['contact_subject']
        contact.contact_message = self.cleaned_data['contact_message']
        if commit:
            contact.save()
            return contact

core/views.py
import os
import pandas as pd
import openpyxl
import json
import datetime

from django.db import connection
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.views import PasswordChangeView, logout_then_login
from django.contrib.auth import (
    login, logout, authenticate, update_session_auth_hash
)
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import User, City, Usr_State, Profile
from .forms import (
    AuthenticationFormWithCaptchaField,
    NewUserForm,
    UserUpdateForm,
    ProfileUpdateForm,
    ContactForm
)
from django.core.mail import EmailMultiAlternatives
from django.urls import reverse_lazy
from .signals import log_user_logout


class PasswordsChangeView(PasswordChangeView):
    model = User
    form_class = PasswordChangeForm
    success_url = reverse_lazy('core:password_changed')


@login_required
def password_changed(request):
    return render(
        request=request,
        template_name='accounts/password_changed.html'
    )


@login_required
def password_change_request(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            messages.success(
                request,
                "Your password was updated successfully."
            )
            return redirect('core:profile')

    else:
        form = PasswordChangeForm(user=request.user)
        args = {'form': form}
        return render(
            request=request,
            template_name="accounts/password_change.html",
            context=args
        )


def password_reset_complete(request):
    return render(
        request=request,
        template_name='accounts/password_reset_complete.html'
    )


def index(request):
    return render(request=request,
                  template_name="core/index.html"
                  )


def entry(request):
    return render(request=request,
                  template_name="core/entry.html"
                  )


def login_request(request):
    if not request.user.is_authenticated:
        if request.method == "POST":
            form = AuthenticationFormWithCaptchaField(request, data=request.POST)
            if form.is_valid():
                username = form.cleaned_data.get('username')
                password = form.cleaned_data.get('password')
                user = authenticate(username=username, password=password)
                login(request, user)
                messages.success(
                    request,
                    f'{username} logged in successfully.'
                )
                return redirect("core:entry")

            elif User.objects.filter(
                    username=form.cleaned_data.get('username')).exists():
                user = User.objects.filter(
                    username=form.cleaned_data.get('username')).values()
                if(user[0]['is_active'] is False):
                    messages.info(
                        request,
                        "Contact the administrator to activate your account!"
                    )
                    return redirect("core:login_request")

                else:
                    return render(
                        request=request,
                        template_name="registration/login.html",
                        context={"form": form}
                    )

            else:
                return render(
                    request=request,
                    template_name="registration/login.html",
                    context={"form": form}
                )
        else:
            form = AuthenticationFormWithCaptchaField()
            return render(
                request=request,
                template_name="registration/login.html",
                context={"form": form}
            )
    else:
        messages.info(
            request,
            '''You are already logged in.  You must log out to log in as
            another user.'''
        )
        return redirect("core:index")


def check_username(request):
    username = request.POST.get('username')
    try:
        user = User.objects.get(username=username)
        return HttpResponse('<div id="username-error" class="error">This username already exists!</div>')
    except User.DoesNotExist:
        return HttpResponse('<div id="username-error" class="success">This username is available.</div>')


def check_email(request):
    email = request.POST.get('email')
    try:
        user = User.objects.get(email=email)
        return HttpResponse('<div id="email-error" class="error">This email already exists!</div>')
    except User.DoesNotExist:
        return HttpResponse('<div id="email-error" class="success">This email is available.</div>')


def register(request):
    if not request.user.is_authenticated:
        if request.method == "POST":
            form = NewUserForm(request.POST)
            if form.is_valid():
                form.save()
                first_name = form.cleaned_data.get("first_name")
                last_name = form.cleaned_data.get("last_name")
                username = form.cleaned_data.get("username")
                email = form.cleaned_data.get("email")
                password = form.cleaned_data.get("password1")

                # START AUTOMATICALLY ALLOW USERS TO ACCESS APP
                ''' user = authenticate(username=username, password=password)
                login(request, user)
                form.send_registration_email()
                messages.success(
                    request,
                    f"New account created for {username}."
                )
                messages.success(
                    request,
                    f"Successfully logged in as {username}."
                ) '''
                # END AUTOMATICALLY ALLOW USERS TO ACCESS APP

                # START USER ACTIVE SET TO FALSE BY DEFAULT
                form.send_registration_email()
                messages.info(
                    request,
                    f"Email sent to Admin to activate your account."
                )
                # END USER ACTIVE SET TO FALSE BY DEFAULT
                return redirect("core:entry")
            else:
                return render(
                    request=request,
                    template_name="registration/register.html",
                    context={"form": form}
                )
        else:

            form = NewUserForm
            return render(
                request=request,
                template_name="registration/register.html",
                context={"form": form}
            )
    else:
        messages.info(
            request,
            '''You are already registered.  You must log out to register
            another user.'''
        )
        return redirect("core:index")


def contact(request):
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            fullname = form.cleaned_data.get("fullname")
            contact_email = form.cleaned_data.get("contact_email")
            contact_subject = form.cleaned_data.get("contact_subject")
            contact_message = form.cleaned_data.get("contact_message")

            subject, from_email, to = contact_subject, os.environ.get(
                'MAIL_USERNAME'), os.environ.get('MAIL_RECIPIENTS')
            text_content = f'''
            Message from ...

            Full Name: {fullname}\n
            Email Address: {contact_email}\n
            Contact Message: {contact_message}
            '''
            html_content = f'''
                <p>Message from core App User...</p>

                <p><strong>Full Name:</strong> {fullname}</p>
                <p><strong>Email Address:</strong> {contact_email}</p>
                <p><strong>Message:</strong> {contact_message}</p>
                '''
            msg = EmailMultiAlternatives(
                subject, text_content, from_email, [to]
            )
            msg.attach_alternative(html_content, "text/html")
            msg.send()

            messages.success(
                request,
                "Email sent!  Thank you for contacting us."
            )
            return redirect("core:index")
        else:
            return render(
                request=request,
                template_name="core/contact.html",
                context={"form": form}
            )

    form = ContactForm
    return render(
        request=request,
        template_name="core/contact.html",
        context={"form": form}
    )


@login_required
def profile(request):

    usr = User.objects.get(id=request.user.id)
    prfle = Profile.objects.get(user_id=request.user.id)

    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=usr)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=prfle)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('core:profile') # Redirect back to profile page

    else:
        u_form = UserUpdateForm(instance=usr)
        p_form = ProfileUpdateForm(instance=prfle)

    city_list = City.objects.all()
    state_list = Usr_State.objects.all()

    context = {
        'u_form': u_form,
        'p_form': p_form,
        'usr': usr,
        'prfle': prfle,
        'city_list': city_list,
        'state_list': state_list
    }

    return render(
        request,
        'core/profile.html',
        context
    )


@login_required
def member_stats(request):

    gender_labels = []
    gender_data = []

templates/core/includes/_footer.html
<footer class="footer bg-primary fixed-bottom">
  Placeholder
</footer>

templates/core/includes/_form_errors.html
{% if form.errors %}
    <ul class="errorlist">
        {% for field in form %}
            {% for error in field.errors %}
                <li>
                    {{ field.label }}:  {{ error|escape }}
                </li>
            {% endfor %}
        {% endfor %}
    </ul>
{% endif %}

{% if form.non_field_errors %}
    <ul class="errorlist">
        {% for err in form.non_field_errors %}
            <li>
              {{ err }}
            </li>
        {% endfor %}
    </ul>
{% endif %}

{% if form.old_password.errors %}
    <ul class="errorlist">
        {% for oldpass_err in form.old_password.errors %}
              <li>
                  {{ oldpass_err }}
              </li>
        {% endfor %}
    </ul>
{% endif %}

{% if form.new_password2.errors %}
    <ul class="errorlist">
        {% for newpass_err in form.new_password2.errors %}
            <li>
                {{ newpass_err }}
            </li>
        {% endfor %}
    </ul>
{% endif %}

templates/core/includes/_messages.html
{% if messages %}
    {% for message in messages%}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
            <div class="alert alert-primary alert-dismissable" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></span></button>
                {{ message }}
            </div>
        {% endif %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            <div class="alert alert-success alert-dismissable" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></span></button>
                {{ message }}
            </div>
        {% endif %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
            <div class="alert alert-warning alert-dismissable" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></span></button>
                {{ message }}
            </div>
        {% endif %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            <div class="alert alert-danger alert-dismissable" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></span></button>
                {{ message }}
            </div>
        {% endif %}
    {% endfor %}
{% endif %}

templates/core/includes/_navbar.html
<!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'core:index' %}">Brand Here</a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarResponsive"
          aria-controls="navbarResponsive"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'core:index' %}"
                >Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'core:contact' %}"
                >Contact Us
                <span class="sr-only">(current)</span>
              </a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'core:calendar' %}">Calendar</a>
            </li>
            <li class="nav-item dropdown">
                <a 
                    class="nav-link dropdown-toggle" 
                    href="#"
                    id="memberNavbarDropdown"
                    role="button"
                    data-toggle="dropdown"
                    aria-haspopup="true"
                    aria-expanded="false"
                >
                        Member
              </a>
                <div class="dropdown-menu" aria-labelledby="memberNavbarDropdown">
                    <a class="dropdown-item" href="{% url 'core:member_stats' %}">Stats</a>
                    <a class="dropdown-item" href="{% url 'core:members' %}">List</a>
                </div>
            </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'core:profile' %}">Profile</a>
              </li>
            <li class="nav-item dropdown">
                <a 
                    class="nav-link dropdown-toggle" 
                    href="#"
                    id="financeNavbarDropdown"
                    role="button"
                    data-toggle="dropdown"
                    aria-haspopup="true"
                    aria-expanded="false"
                >
                        Finance
            </a>
                <div class="dropdown-menu" aria-labelledby="financeNavbarDropdown">
                    <a class="dropdown-item" href="{% url 'core:finance_chart' %}">Chart</a>
                    <a class="dropdown-item" href="{% url 'core:finances' %}">Table</a>
                </div>
            </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'core:logout_request' %}">Logout</a>
              </li>
              <li>
                <a class="nav-link disabled" href="#">Logged in as {{ user.username}}</a>
              </li>
            {% else %}
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'core:register' %}">Register</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'core:login_request' %}">Login</a>
                </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>