core/urls.py
from django.urls import path, reverse_lazy
from . import views
from .views import PasswordsChangeView
from django.contrib.auth.views import (
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView)

app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),
    path("core/entry", views.entry, name="entry"),
    path("accounts/logout/", views.logout_request, name="logout_request"),
    path("accounts/login/", views.login_request, name="login_request"),
    path("register/", views.register, name="register"),
    path("profile/", views.profile, name="profile"),
    path(
        "profile/password/",
        PasswordsChangeView.as_view(
            template_name='accounts/password_change.html'
        )
    ),
    path(
        "accounts/password_changed/",
        views.password_changed,
        name="password_changed"),
    path(
        "accounts/password-reset/",
        PasswordResetView.as_view(
            template_name='accounts/password_reset.html',
            success_url=reverse_lazy('core:password_reset_done')
        ),
        name='password_reset'
    ),
    path(
        "accounts/password-reset/done/",
        PasswordResetDoneView.as_view(
            template_name='accounts/password_reset_done.html'
        ),
        name='password_reset_done'),
    path(
        "accounts/password-reset-confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name='accounts/password_reset_confirm.html',
            success_url=reverse_lazy('core:password_reset_complete')
        ),
        name='password_reset_confirm'),
    path(
        "accounts/password-reset-complete/",
        PasswordResetCompleteView.as_view(
            template_name='accounts/password_reset_complete.html'
        ),
        name='password_reset_complete'),
    path("contact/", views.contact, name='contact'),
    path("member_stats/", views.member_stats, name='member_stats'),
    path("members/", views.members, name='members'),
    path("finance_chart/", views.finance_chart, name='finance_chart'),
    path("finances/", views.finances, name='finances'),
    path("calendar/", views.calendar, name='calendar'),
]

htmx_urlpatterns = [
    path(
        'register/check_username/', views.check_username, name='check_username'
        ),
    path(
        'register/check_email/', views.check_email, name='check_email'
        ),
]

urlpatterns += htmx_urlpatterns

proj/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',  include('core.urls')),
]

if settings.DEBUG:
    urlpatterns  += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
import uuid

from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from PIL import Image


class Usr_State(models.Model):
    name = models.CharField(max_length=75)

    class Meta:
        verbose_name_plural = "Usr_States"

    def __str__(self):
        return self.name


class City(models.Model):
    selected_state = models.ForeignKey(
        Usr_State,
        verbose_name="Usr_States",
        on_delete=models.CASCADE
        )
    name = models.CharField(max_length=75)

    class Meta:
        verbose_name_plural = "Cities"

    def __str__(self):
        return self.name


class Org(models.Model):
    name = models.CharField(max_length=150)
    org_city = models.ForeignKey(
        City,
        verbose_name="Cities",
        on_delete=models.CASCADE
        )
    org_state = models.ForeignKey(
        Usr_State,
        verbose_name="Usr_States",
        on_delete=models.CASCADE
        )

    class Meta:
        verbose_name_plural = "Orgs"

    def __str__(self):
        return self.name + '-' + self.org_city.name + '-' + self.org_state.name


class Ministry(models.Model):
    name = models.CharField(max_length=150)
    org = models.ForeignKey(
        Org,
        verbose_name="Orgs",
        on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "Ministries"

    def __str__(self):
        return self.name + '_' + self.org.name


class MinistryRole(models.Model):
    name = models.CharField(max_length=150)
    ministry_department = models.ForeignKey(
        Ministry,
        verbose_name="Ministries",
        default=None,
        on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "MinistryRoles"

    def __str__(self):
        return self.name + ' - ' + self.ministry_department.name


class Profile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE) # Delete profile when user is deleted
    uuid = models.UUIDField(primary_key=False, default=uuid.uuid4, editable=False)

    class Role(models.TextChoices):
        ADMIN = ('ADMIN', 'Admin')
        LEADER = ('LEADER', 'Leader')
        MEMBER = ('MEMBER', 'Member')
        GUEST = ('GUEST', 'Guest')

    class Gender(models.TextChoices):
        FEMALE = ('Female', 'Female')
        MALE = ('Male', 'Male')

    class Marital_Status(models.TextChoices):
        MARRIED = ('Married', 'Married')
        SINGLE = ('Single', 'Single')
        DIVORCED = ('Divorced', 'Divorced')
        WIDOWED = ('Widowed', 'Widowed')

    class Tier(models.TextChoices):
        ONE = ('1', '1')
        TWO = ('2', '2')
        THREE = ('3', '3')

    gender = models.CharField(
        name='gender',
        max_length=10,
        choices=Gender.choices,
        null=True,
        blank=True
    )

    marital_status = models.CharField(
        name='marital_status',
        max_length=10,
        choices=Marital_Status.choices,
        null=True,
        blank=True
    )

    tier = models.CharField(
        name='tier',
        max_length=10,
        choices=Tier.choices,
        null=True,
        blank=True
    )
    street_number = models.IntegerField(blank=True,null=True)
    street_name = models.CharField(max_length=50, blank=True,null=True)
    usr_city = models.ForeignKey(
        City,
        verbose_name="Cities",
        blank=True,
        null=True,
        on_delete=models.CASCADE
        )
    usr_state = models.ForeignKey(
        Usr_State,
        blank=True,
        null=True,
        verbose_name="Usr_States",
        on_delete=models.CASCADE
        )
    postal_code = models.IntegerField(blank=True,null=True)
    image = models.ImageField(
        upload_to="profile_pic",
        default='default.png'
        )


    def __str__(self):
        return self.user.first_name + ' ' + self.user.last_name

    # Override the save method of the model
    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)

        img = Image.open(self.image.path) # Open image
        print(self.image.path)

        # resize image
        if img.height > 150 or img.width > 150:
            output_size = (150, 150)
            img.thumbnail(output_size) # Resize image
            img.save(self.image.path) # Save it again and override the larger image


class Contact(models.Model):
    fullname = models.CharField(max_length=75)
    contact_email = models.EmailField()
    contact_subject = models.CharField(max_length=50)
    contact_message = models.TextField()
    inserted_date = models.DateTimeField(
        default=timezone.now
    )

    class Meta:
        verbose_name_plural = "Catalog_Contacts"

    def __str__(self):
        return self.fullname

core/forms.py
from django import forms
from django.contrib.auth.forms import (
    AuthenticationForm, UserCreationForm, UserChangeForm
)
from django.contrib.auth.models import User
from .models import Profile, Contact
from django.core.exceptions import ValidationError
from captcha.fields import ReCaptchaField
from core.tasks import send_registration_email_task


class AuthenticationFormWithCaptchaField(AuthenticationForm):
    captcha = ReCaptchaField(
        public_key='6Le6CNkdAAAAAM0erjmCJJ_YW_tnVDhfFmvYHEQX',
        private_key='6Le6CNkdAAAAAKUVozivgonzS4yEnlfH8Ai0Ck2Y',
    )


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)
    captcha = ReCaptchaField(
        public_key='6Le6CNkdAAAAAM0erjmCJJ_YW_tnVDhfFmvYHEQX',
        private_key='6Le6CNkdAAAAAKUVozivgonzS4yEnlfH8Ai0Ck2Y',
    )

    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
            "password1",
            "password2"
        )

    def send_registration_email(self):
        send_registration_email_task.delay(
            self.cleaned_data['first_name'],
            self.cleaned_data['last_name'],
            self.cleaned_data['username'],
            self.cleaned_data['email']
        )

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.is_active = False # REMOVE LINE TO ALLOW USERS AUTO ACCESS TO APP
        if commit:
            user.save()
            return user


# Create a UserUpdateForm to update a username and email
class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']



class ProfileUpdateForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = (
            'image',
            'gender',
            'marital_status',
            'street_number',
            'street_name',
            'usr_city',
            'usr_state',
            'postal_code'
        )


class ContactForm(forms.ModelForm):
    captcha = ReCaptchaField(
        public_key='6Le6CNkdAAAAAM0erjmCJJ_YW_tnVDhfFmvYHEQX',
        private_key='6Le6CNkdAAAAAKUVozivgonzS4yEnlfH8Ai0Ck2Y',
    )

    class Meta:
        model = Contact
        fields = (
            'fullname',
            'contact_email',
            'contact_subject',
            'contact_message'
        )

    def save(self, commit=True):
        contact = super(ContactForm, self).save(commit=False)
        contact.fullname = self.cleaned_data['fullname']
        contact.contact_email = self.cleaned_data['contact_email']
        contact.contact_subject = self.cleaned_data['contact_subject']
        contact.contact_message = self.cleaned_data['contact_message']
        if commit:
            contact.save()
            return contact

templates/core/calendar.html
{% extends 'core/layout.html' %}
{% block title %} Calender {% endblock %}
{% load static %}
{% block body %}
{% load widget_tweaks %}
<div class="page-content">
    <legend class="border-bottom mb-4">
        Calender
    </legend>
    <iframe  class="responsive-iframe"  src="https://calendar.google.com/calendar/embed?height=600&wkst=1&bgcolor=%23ffffff&ctz=America%2FChicago&showNav=0&showTitle=0&showDate=0&showPrint=0&src=bGhib2UyMDEzQGdtYWlsLmNvbQ&src=ZW4udXNhI2hvbGlkYXlAZ3JvdXAudi5jYWxlbmRhci5nb29nbGUuY29t&color=%23039BE5&color=%23009688" style="border:solid 1px #777" width="1280" height="720" frameborder="0" scrolling="no"></iframe>
{% endblock %}

templates/core/contact.html
{% extends 'core/layout.html' %}
{% block title %} Contact {% endblock %}
{% load static %}
{% block body %}
{% load widget_tweaks %}
<div class="page-content">
    <legend class="border-bottom mb-4">
        Contact Us
    </legend>
    <div>
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="fullname">Full Name</label>
                <input type="text" class="form-control" name="fullname" required=true>
            <div>
            <div class="form-group">
                <label for="contact_email">Email</label>
                <input type="text" class="form-control" name="contact_email" required=true>
            </div>
            <div class="form-group">
                <label for="contact_subject">Subject</label>
                <input type="text" class="form-control" name="contact_subject" required=true>
            </div>
            <div class="form-group">
                <label for="contact_message">Message</label>
                <textarea class="form-control" name="contact_message" row="3" required=true></textarea>
            </div>
            <br />
              <div class="form-group">
                {% render_field form.captcha%}
              </div>
            <br />
            <div class="form-group">
                <button id="contact" class="btn btn-sm btn-primary" type="submit">Submit</button>
            </div>
        </form>
    </div>
  </div>
{% endblock %}

templates/core/entry.html
{% extends 'core/layout.html' %}
{% load static %}
{% block title %}Home{% endblock %}
{% block body %}
<div class="page-content">
  <div class="container-fluid">
    <h1>Entry Page</h1>
    </div>
  </div>
{% endblock %}

templates/core/finance_chart.html
{% extends 'core/layout.html' %}
{% load static %}
{% block title %}Budget Chart{% endblock %}
{% block body %}
<div class="page-content">
    <div class="container-fluid">
        <div class="row">
            <canvas id="financeChart"></canvas>
        </div>
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-autocolors"></script>
  <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@2"></script>
  <script src="https://unpkg.com/chart.js-plugin-labels-dv/dist/chartjs-plugin-labels.min.js"></script>
  <script>
      const ctx = document.getElementById("financeChart");
      const myFinanceChart = new Chart(ctx, {
        type: "bar",
        data: {
          labels: {{labels|safe}},
          datasets: [{
            data: {{values|safe}}
          }]
        },
        options: {
            responsive: true,
            maintainAspectRatio: true,
            plugins: {
                legend: {
                    display: false
                },
                title: {
                    display: true,
                    text: "Church Budget",
                    font: {
                        size: 20
                    }
                }
            }
        }
      });
</script>
{% endblock %}

templates/core/finances.html
{% extends 'core/layout.html' %}
{% load static %}
{% block title %}Budget{% endblock %}
{% block body %}
<div class="page-content">
    <div class="container-fluid">
        <table id="financeTable" class="cell-border compact hover">
            <thead>
                <tr>
                    <th class="fit">Month Year</th>
                    <th class="fit">Number of Tithe Donors</th>
                    <th class="fit">Tithe Amount</th>
                    <th class="fit">Number of Church Budget Donors</th>
                    <th class="fit">Church Budget Amount</th>
                    <th class="fit">Total Local Funds Amount</th>
                </tr>
            </thead>
            <tbody>
                {% for record in data %}
                    <tr>
                        <td class="fit">{{record.month_year}}</td>
                        <td class="fit">{{record.number_tithe_donors}}</td>
                        <td class="fit">{{record.tithe}}</td>
                        <td class="fit">{{record.number_church_budget_donors}}</td>
                        <td class="fit">{{record.church_budget}}</td>
                        <td class="fit">{{record.total_local_funds}}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

templates/core/index.html
{% extends 'core/layout.html' %}
{% load static %}
{% block title %}Home{% endblock %}
{% block body %}
<div class="page-content">
  <div class="container-fluid">
    <h1>Landing Page Placeholder</h1>
    </div>
  </div>
{% endblock %}

templates/core/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
      integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
      crossorigin="anonymous"
    />
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
      integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
      integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
      crossorigin="anonymous"
    ></script>

    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
    

    {% load static %}
    <!-- Custom CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/core_styles.css' %}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>

    <!-- HTMX -->
    <script src="https://unpkg.com/htmx.org@1.8.4"></script>

    <!-- Fontawesome-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Data Tables -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.2/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.2/js/jquery.dataTables.min.js"></script>


  <title>
    {% block title %} Home {% endblock %}
  </title>
  </head>

  <body>
    <!-- Page Content -->
    <div class="container-fluid">
      <br />
      {% include "core/includes/_navbar.html" %} <!-- Navbar -->
      {% include "core/includes/_messages.html" %} <!-- Messages -->
      {% include "core/includes/_form_errors.html" %} <!-- Form Errors -->
      {% block body %}
      {% endblock %}
      {% include "core/includes/_footer.html" %} <!-- Footer -->
    </div>
    <!-- End container class-->

    <script type="text/JavaScript">
      setTimeout(function () {

        // Closing the alert
        $('.alert').hide(500);
      }, 5000);

      $(document).ready( function () {
          $('#memTable').DataTable({
            'columnDefs': [
              {
                  "targets":[0,3,4,5,6, 9, 10],
                  "className": "text-center"
            }
          ]
          });
      } );

      $(document).ready( function () {
        $('#financeTable').DataTable({
          'columnDefs': [
            {
                "targets":["_all"],
                "className": "text-center"
          }
        ]
        });
    } );
    </script>

  </body>
</html>

templates/core/members.html
{% extends 'core/layout.html' %}
{% load static %}
{% block title %}Members{% endblock %}
{% block body %}
<div class="page-content">
    <div class="container-fluid">
        <h1>Membership List</h1>
    </div>
    <br />
    <hr>
    <div>
        <table id="memTable" class="cell-border compact hover">
            <thead>
                <tr>
                    <th class="fit">View</th>
                    <th class="fit">Last Name</th>
                    <th class="fit">First Name</th>
                    <th class="fit">Gender</th>
                    <th class="fit">Marital Status</th>
                    <th class="fit">Tier</th>
                    <th class="fit">Street Number</th>
                    <th class="fit">Street Name</th>
                    <th class="fit">City</th>
                    <th class="fit">State</th>
                    <th class="fit">Postal Code</th>
                </tr>
            </thead>
            <tbody>
                {% for member in data_list %}
                    <tr>
                        <td><a href="#"><i class="fa fa-eye" aria-hidden="true"></i></a></td>
                        <td class="fit">{{member.last_name}}</td>
                        <td class="fit">{{member.first_name}}</td>
                        <td class="fit">{{member.gender}}</td>
                        <td class="fit">{{member.marital_status}}</td>
                        <td class="fit">{{member.tier}}</td>
                        <td class="fit">{{member.street_number}}</td>
                        <td class="fit">{{member.street_name}}</td>
                        <td class="fit">{{member.city}}</td>
                        <td class="fit">{{member.state_abbrev}}</td>
                        <td class="fit">{{member.postal_code}}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
  </div>
{% endblock %}

templates/core/profile.html
{% extends 'core/layout.html' %}
{% block title %} Edit Profile {% endblock %}
{% block body %}
<div class="page-content">
  <div class="container-fluid">
    <div class="media">
      <img
        class="account-img"
        src="{{ user.profile.image.url }}"
      />
      <div class="media-body">
      </div>
    </div>
    <br>
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Profile Info</legend>
        <div class="form-group">
          <label for="current_image">Current Image:  </label>
          <a id="current_image" href="/media/{{ user.profile.image }}">{{ user.profile.image }}</a>
        </div>
        <div class="form-group">
          <label>Change:  </label>
          <input type="file" name="image" accept="image/" id="id_image">
        </div>
        <br>
        <div class="form-group">
          <div class="row">
            <div class="col-sm-3">
              <label for="id_first_name">First Name</label>
              <input type="text" class="form-control form-control-sm" name="first_name" value="{{ user.first_name }}" required id="id_first_name" readonly="true">
            </div>
            <div class="col-sm-3">
              <label for="id_last_name">Last Name</label>
              <input type="text" class="form-control form-control-sm" name="last_name" value="{{ user.last_name }}" required id="id_last_name">
            </div>
            <div class="col-sm-3">
              <label for="id_username">Username</label>
              <input type="text" class="form-control form-control-sm" name="username" value="{{ user.username }}" required id="id_username" readonly="true">
            </div>
            <div class="col-sm-3">
              <label for="id_email">Email</label>
              <input type="text" class="form-control form-control-sm" name="email" value="{{ user.email }}" required id="id_email">
            </div>
          </div>
          <div class="row">
            <div class="col-sm-3">
              <label for="id_gender">Gender:</label>
              <select class="form-control form-control-sm" name="gender" id="id_gender">
                <option
                    selected="true"
                    value='{{ prfle.gender }}'
                  >
                    {{ prfle.gender }}
                  </option>
                  {% if prfle.gender == "Female" %}
                    <option value="Male">Male</option>
                  {% else %}
                    <option value="Female">Female</option>
                  {% endif %}
              </select>
            </div>
            <div class="col-sm-3">
              <label for="id_marital_status">Marital status:</label>
              <select class="form-control form-control-sm" name="marital_status" id="id_marital_status">
                <option
                    selected="true"
                    value='{{ prfle.marital_status }}'
                  >
                    {{ prfle.marital_status }}
                </option>
                {% if prfle.marital_status == "Married" %}
                  <option value="Single">Single</option>
                  <option value="Divorced">Divorced</option>
                  <option value="Widowed">Widowed</option>
                {% elif prfle.marital_status == "Single" %}
                  <option value="Married">Married</option>
                  <option value="Divorced">Divorced</option>
                  <option value="Widowed">Widowed</option>
                {% elif prfle.marital_status == "Divorced" %}
                  <option value="Married">Married</option>
                  <option value="Single">Single</option>
                  <option value="Widowed">Widowed</option>
                {% else %}
                  <option value="Married">Married</option>
                  <option value="Single">Single</option>
                  <option value="Divorced">Divorced</option>
                {% endif %}
              </select>
            </div>
            <div class="col-sm-3">
              <label for="id_street_number">Street number:</label>
              <input class="form-control form-control-sm" type="number" name="street_number" value="302" id="id_street_number">
            </div>
            <div class="col-sm-3">
              <label for="id_street_name">Street name:</label>
              <input class="form-control form-control-sm" type="text" name="street_name" value="Alamosa Pl" maxlength="50" id="id_street_name">
            </div>
          </div>
          <div class="row">
            <div class="col-sm-3">
              <label for="id_usr_city">Cities:</label>
              <select class="form-control form-control-sm" name="usr_city" id="id_usr_city">
                <option
                    selected="true"
                    value='{{ prfle.usr_city_id }}'
                  >
                    {{ prfle.usr_city }}
                  </option>
                  {% for c in city_list %}
                    <option value="{{ c.id }}">
                      {{ c.name }}
                    </option>
                  {% endfor %}
              </select>
            </div>
            <div class="col-sm-3">
              <label for="id_usr_state">States:</label>
              <select class="form-control form-control-sm" name="usr_state" id="id_usr_state">
                <option
                    selected="true"
                    value='{{ prfle.usr_state_id }}'
                  >
                    {{ prfle.usr_state }}
                  </option>
                  {% for s in state_list %}
                    <option value="{{ s.id }}">
                      {{ s.name }}
                    </option>
                  {% endfor %}
              </select>
            </div>
            <div class="col-sm-3">
              <label for="id_postal_code">Postal Code:</label>
              <input class="form-control form-control-sm" type="number" name="postal_code" id="id_postal_code" value="{{ prfle.postal_code }}">
            </div>
          </div>
          <div class="row">
            <div class="col-sm-3">
              <button class="btn btn-sm btn-outline-info" type="submit">Update</button>
            </div>
          </div>
        </div>
      </fieldset>
    </form>
  </div>
</div>
{% endblock %}